name: APM 发行版构建
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
  buildAPK:
    runs-on: ubuntu-latest
    name: 构建 APK
    permissions:
      contents: write
    steps:
      - name: 检出
        uses: actions/checkout@v4

      - name: python version_bump.py
        run: |
          python ./scripts/version_bump.py

      - name: 获取分支名称
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: 获取当前日期
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: 设置 JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 设置 Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: '创建 env 文件'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ secrets.SENTRY_PROPERTIES }}" > ./android/sentry.properties

      - name: alias yarn.cmd to yarn
        run: alias yarn.cmd="yarn"

      - name: 获取最新提交标签
        id: get_commit_tag
        run: |
          COMMIT_TAG=$(git describe --tags --abbrev=0 || echo "v2.18.1")
          echo "COMMIT_TAG=${COMMIT_TAG}" >> $GITHUB_ENV

      - name: 显示提交标签
        run: |
          echo "Commit Tag: $COMMIT_TAG"

      - name: 添加构建签名密钥
        run: |
          git submodule update --init --recursive
          echo "${{ secrets.RELEASE_SIGN_PWD }}" >> ./android/gradle.properties

      - name: 提交
        run: |
          git config --global user.email 88823709+TC999@users.noreply.github.com 
          git config --global user.name TC999
          git commit -m "build: release version bump" -a

      - name: python fixHTTP
        run: |
          python ./scripts/fixHTTP.py

      - name: 构建 jks 签名
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'noxupload.jks'
          fileDir: './android/app'
          encodedString: ${{ secrets.SIGNED_KEY_BASE64 }}

      - name: 安装依赖
        run: yarn install; yarn postinstall

      - name: 清除生成构建
        run: rm -rf android/app/build/generated/

      #- name: codepush to prod
      #  run: |
      #    npm install -g appcenter-cli
      #    yarn codepush --token ${{secrets.CODEPUSH_ACCESS_TOKEN}}
      #    yarn codepush:promote --token ${{secrets.CODEPUSH_ACCESS_TOKEN}}

      - name: gradle 构建 APK
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease

      - name: 发布 APK
        uses: softprops/action-gh-release@v2
        with:
          name: '发行版 ${{env.COMMIT_TAG}}'
          tag_name: '${{env.COMMIT_TAG}}'
          files: android/app/build/outputs/apk/release/*.apk
          generate_release_notes: true

  buildAAB:
    runs-on: ubuntu-latest
    name: 构建 AAB
    permissions:
      contents: write
    steps:
      - name: 检出
        uses: actions/checkout@v4

      - name: python version_bump.py
        run: |
          python ./scripts/version_bump.py

      - name: 获取分支名称
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: 获取分支名称
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: 设置 JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 设置 Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "APPSTORE=true" >> .env
          echo "${{ secrets.SENTRY_PROPERTIES }}" > ./android/sentry.properties

      - name: alias yarn.cmd to yarn
        run: alias yarn.cmd="yarn"

      - name: 获取最新提交标签
        id: get_commit_tag
        run: |
          COMMIT_TAG=$(git describe --tags --abbrev=0 || echo "v2.18.1")
          echo "COMMIT_TAG=${COMMIT_TAG}" >> $GITHUB_ENV

      - name: 显示提交标签
        run: |
          echo "Commit Tag: $COMMIT_TAG"

      - name: 提交
        run: |
          git config --global user.email 88823709+TC999@users.noreply.github.com 
          git config --global user.name TC999
          git commit -m "build: release version bump" -a
          git tag $COMMIT_TAG-fdroid

      - name: 推送更改到 master 分支
        uses: ad-m/github-push-action@master
        with:
          tags: true

      - name: 添加构建签名密钥
        run: |
          git submodule update --init --recursive
          echo "${{ secrets.RELEASE_SIGN_PWD }}" >> ./android/gradle.properties

      - name: python fixHTTP
        run: |
          python ./scripts/fixHTTP.py

      - name: 构建 jks 签名
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'noxupload.jks'
          fileDir: './android/app'
          encodedString: ${{ secrets.SIGNED_KEY_BASE64 }}

      - name: 安装依赖
        run: yarn install; yarn postinstall

      - name: 清除生成构建
        run: rm -rf android/app/build/generated/

      - name: gradle 构建 AAB
        run: cd android && chmod +x gradlew && ./gradlew bundleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: outputAAB
          path: android/app/build/outputs/bundle/release/*.aab # or path/to/artifact

      # - uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
      #     packageName: com.noxplay.noxplayer
      #     releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
      #     track: internal
      #     #changesNotSentForReview: true

  buildIPA:
    runs-on: macos-14
    name: build IPA
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: 获取分支名称
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: 设置 JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "APPSTORE=true" >> .env
          echo "${{ secrets.SENTRY_PROPERTIES }}" > ./ios/sentry.properties
          git submodule update --init --recursive

      - name: alias yarn.cmd to yarn
        run: alias yarn.cmd="yarn"

      - name: Get Recent Commit Tag
        id: get_commit_tag
        run: |
          COMMIT_TAG=$(git describe --tags --abbrev=0)
          echo "COMMIT_TAG=${COMMIT_TAG}" >> $GITHUB_ENV

      - name: Display Commit Tag
        run: |
          echo "Commit Tag: $COMMIT_TAG"

      - name: Install dependencies
        run: yarn install; yarn postinstall

      - name: Pod Install
        run: cd ios && rm Podfile.lock && pod install --repo-update

      - name: python fixHTTP
        run: |
          python ./scripts/fixHTTP.py
          python ./scripts/fixiOSBuild.py

      - name: build
        run: cd ios && xcodebuild -scheme APM -workspace example.xcworkspace -configuration Release clean archive -archivePath "build/APM.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: archive to ipa
        run: |
          cd ios
          mkdir build/Payload
          mv build/APM.xcarchive/Products/Applications/AzusaPlayer.app build/Payload/AzusaPlayer.app
          cd build
          zip -r APM.ipa Payload/

      - name: Release IPA
        uses: softprops/action-gh-release@v2
        with:
          name: 'Release ${{env.COMMIT_TAG}}'
          tag_name: '${{env.COMMIT_TAG}}'
          files: ios/build/APM.ipa
          generate_release_notes: true
